export const YOUTUBE_LIBRARY_LOADED = 'YOUTUBE_LIBRARY_LOADED'
export const REQUEST = 'REQUEST'
export const SUCCESS = 'SUCCESS'
export const FAILURE = 'FAILURE'
export const AMOUNT_TRENDING_VIDEOS = 12